<?php
/*
@edooRef: @theme_bheem/layout
 */

defined('MOODLE_INTERNAL') || die();

$templatecontext = [
    'sitename'                  => format_string($SITE->shortname, true, ['context' => context_course::instance(SITEID), "escape" => false]),
    'output'                    => $OUTPUT,
    'pageheading'               => $pageheading,
    'leftblocks'                => $leftblocks,
    'user_profile_picture'      => new moodle_url('/user/pix.php/'.$USER->id.'/f1.jpg'),
    'profile_icon_username'     => $edooProfileIconUsername,
    'login_url'                 => $login_url,
    'signup_url'                => $signup_url,
    'isloggedin'                => $isloggedin,
    'sidepreblocks'             => $blockshtml,
    'hasblocks'                 => $hasblocks,
    'bodyattributes'            => $bodyattributes,
    'primarymoremenu'           => $primarymenu['moremenu'],
    'secondarymoremenu'         => $secondarynavigation ?: false,
    'mobileprimarynav'          => $primarymenu['mobileprimarynav'],
    'usermenu'                  => $primarymenu['user'],
    'langmenu'                  => $primarymenu['lang'],
    'headercontent'             => $headercontent,
    'overflow'                  => $overflow,
    'addblockbutton'            => $addblockbutton,
    'blocks_fullwidth_top'      => $blocks_fullwidth_top,
    'blocks_fullwidth_bottom'   => $blocks_fullwidth_bottom,
    'blocks_above_content'      => $blocks_above_content,
    'has_blocks_above_content'  => !empty($blocks_above_content),
    'blocks_below_content'      => $blocks_below_content,
    'has_blocks_below_content'  => !empty($blocks_below_content),
    'has_blocks_fullwidth_top'  => !empty($blocks_fullwidth_top),
    'regionmainsettingsmenu'    => $regionmainsettingsmenu,
    'hasregionmainsettingsmenu' => !empty($regionmainsettingsmenu),
    'edoo_globalsearch_navbar' => $edoo_globalsearch_navbar,
    'logo_visibility'           => $logo_visibility,
    'main_logo'                 => $main_logo,
    'logo_styles'               => $logo_styles,
    'mobile_logo'               => $mobile_logo,
    'mobile_logo_styles'        => $mobile_logo_styles,
    'header_search_bar'         => $header_search,
    'header_btn_url'            => $header_btn_url,
    'header_left_btn_text'      => $header_left_btn_text,
    'header_left_btn_url'       => $header_left_btn_url,
    'header_btn_icon'           => $header_btn_icon,
    'header_left_btn_icon'      => $header_left_btn_icon,
    'category_title'            => $category_title,
    'category_content'          => $category_content,

    'footer_logo_visibility'    => $footer_logo_visibility,
    'main_footer_logo'          => $main_footer_logo,
    'footer_logo_styles'        => $footer_logo_styles,

    'social_target_href' => $social_target_href,
    'edoo_facebook_url' => get_config('theme_bheem', 'edoo_facebook_url'),
    'edoo_twitter_url' => get_config('theme_bheem', 'edoo_twitter_url'),
    'edoo_instagram_url' => get_config('theme_bheem', 'edoo_instagram_url'),
    'edoo_pinterest_url' => get_config('theme_bheem', 'edoo_pinterest_url'),
    'edoo_dribbble_url' => get_config('theme_bheem', 'edoo_dribbble_url'),
    'edoo_google_url' => get_config('theme_bheem', 'edoo_google_url'),
    'edoo_youtube_url' => get_config('theme_bheem', 'edoo_youtube_url'),
    'edoo_vk_url' => get_config('theme_bheem', 'edoo_vk_url'),
    'edoo_500px_url' => get_config('theme_bheem', 'edoo_500px_url'),
    'edoo_behance_url' => get_config('theme_bheem', 'edoo_behance_url'),
    'edoo_digg_url' => get_config('theme_bheem', 'edoo_digg_url'),
    'edoo_flickr_url' => get_config('theme_bheem', 'edoo_flickr_url'),
    'edoo_foursquare_url' => get_config('theme_bheem', 'edoo_foursquare_url'),
    'edoo_linkedin_url' => get_config('theme_bheem', 'edoo_linkedin_url'),
    'edoo_medium_url' => get_config('theme_bheem', 'edoo_medium_url'),
    'edoo_meetup_url' => get_config('theme_bheem', 'edoo_meetup_url'),
    'edoo_snapchat_url' => get_config('theme_bheem', 'edoo_snapchat_url'),
    'edoo_tumblr_url' => get_config('theme_bheem', 'edoo_tumblr_url'),
    'edoo_vimeo_url' => get_config('theme_bheem', 'edoo_vimeo_url'),
    'edoo_wechat_url' => get_config('theme_bheem', 'edoo_wechat_url'),
    'edoo_whatsapp_url' => get_config('theme_bheem', 'edoo_whatsapp_url'),
    'edoo_wordpress_url' => get_config('theme_bheem', 'edoo_wordpress_url'),
    'edoo_weibo_url' => get_config('theme_bheem', 'edoo_weibo_url'),
    'edoo_telegram_url' => get_config('theme_bheem', 'edoo_telegram_url'),
    'edoo_moodle_url' => get_config('theme_bheem', 'edoo_moodle_url'),
    'edoo_amazon_url' => get_config('theme_bheem', 'edoo_amazon_url'),
    'edoo_slideshare_url' => get_config('theme_bheem', 'edoo_slideshare_url'),
    'edoo_soundcloud_url' => get_config('theme_bheem', 'edoo_soundcloud_url'),
    'edoo_leanpub_url' => get_config('theme_bheem', 'edoo_leanpub_url'),
    'edoo_xing_url' => get_config('theme_bheem', 'edoo_xing_url'),
    'edoo_bitcoin_url' => get_config('theme_bheem', 'edoo_bitcoin_url'),
    'edoo_twitch_url' => get_config('theme_bheem', 'edoo_twitch_url'),
    'edoo_github_url' => get_config('theme_bheem', 'edoo_github_url'),
    'edoo_gitlab_url' => get_config('theme_bheem', 'edoo_gitlab_url'),
    'edoo_forumbee_url' => get_config('theme_bheem', 'edoo_forumbee_url'),
    'edoo_trello_url' => get_config('theme_bheem', 'edoo_trello_url'),
    'edoo_weixin_url' => get_config('theme_bheem', 'edoo_weixin_url'),
    'edoo_slack_url' => get_config('theme_bheem', 'edoo_slack_url'),

    'footer_copyright'       => $footer_copyright,
    'banner_image'     => $banner_image,
    'banner_shape'     => $banner_shape,
    'back_to_top'            => $back_to_top == 0,
    'hide_global_banner'     => $hide_global_banner == 0,
    'hide_guest_access_curriculum'            => $hide_guest_access_curriculum == 0,

    'favicon'                   => $favicon,
    'footer_column_1' => $footer_column_1,
    'footer_column_2' => $footer_column_2,
    'footer_column_3' => $footer_column_3,
    'footer_column_4' => $footer_column_4,
    'footer_column_5' => $footer_column_5,
    'footer_col_1_class' => $footer_col_1_class,
    'footer_col_2_class' => $footer_col_2_class,
    'footer_col_3_class' => $footer_col_3_class,
    'footer_col_4_class' => $footer_col_4_class,
    'footer_col_5_class' => $footer_col_5_class,
    'footer_col_1_title' => get_config('theme_bheem', 'footer_col_1_title'),
    'footer_col_1_body' => get_config('theme_bheem', 'footer_col_1_body'),
    'footer_col_2_title' => get_config('theme_bheem', 'footer_col_2_title'),
    'footer_col_2_body' => get_config('theme_bheem', 'footer_col_2_body'),
    'footer_col_3_title' => get_config('theme_bheem', 'footer_col_3_title'),
    'footer_col_3_body' => get_config('theme_bheem', 'footer_col_3_body'),
    'footer_col_4_title' => get_config('theme_bheem', 'footer_col_4_title'),
    'footer_col_4_body' => get_config('theme_bheem', 'footer_col_4_body'),
    'footer_col_5_title' => get_config('theme_bheem', 'footer_col_5_title'),
    'footer_col_5_body' => get_config('theme_bheem', 'footer_col_5_body'),

];
$PAGE->requires->jquery();